# Generated by Django 5.0.6 on 2026-04-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemiconChat',
            fields=[
            ],
            options={
                'verbose_name': 'SemiconChat',
                'verbose_name_plural': 'SemiconChat',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chat.chatsession',),
        ),
    ]
