# Generated by Django 5.0.6 on 2026-04-23 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_semiconchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('table_text', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='excel_context', to='chat.chatsession')),
            ],
        ),
    ]
