# Generated by Django 5.0.6 on 2026-04-20 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.CharField(choices=[('lithography', 'Lithography'), ('etching', 'Etching'), ('deposition', 'Deposition'), ('cmp', 'CMP'), ('implantation', 'Ion Implantation'), ('diffusion', 'Diffusion'), ('metallization', 'Metallization'), ('inspection', 'Inspection & Metrology'), ('general', 'General')], default='general', max_length=50)),
                ('stage', models.CharField(choices=[('FEOL', 'Front End of Line (FEOL)'), ('BEOL', 'Back End of Line (BEOL)'), ('general', 'General')], default='general', max_length=10)),
                ('doc_type', models.CharField(choices=[('sop', 'SOP / Process Recipe'), ('research_paper', 'Research Paper'), ('equipment_spec', 'Equipment Specification'), ('defect_library', 'Defect Library'), ('training', 'Training Material'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_indexed', models.BooleanField(default=False)),
                ('indexing_error', models.TextField(blank=True, default='')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
